CREATE TABLE IF NOT EXISTS flags (
  id INTEGER PRIMARY KEY,
  flag CHAR(255)
  );

INSERT INTO flags (id, flag) VALUES (1, 'flag{TFZ4HACMWejgqsUyXPDfakx3NDU1HK}') ON DUPLICATE KEY UPDATE flag = VALUES(flag);
