import asyncssh

from asyncssh import SSHClientConnection
from dataclasses import dataclass

from cochise.common import get_or_fail

@dataclass
class SSHConnection:
    host: str = 'localhost'
    username: str = 'changeme'
    password: str = 'changeme'
    port: int = 22
    timeout: int = 600

    _conn: SSHClientConnection|None = None

    async def connect(self):
        self._conn = await asyncssh.connect(self.host, port=self.port, username=self.username, password=self.password, known_hosts=None)

    # execute the command. We redirect stderr to stdout (to have a unified output stream)
    # and configure a timeout.
    async def run(self, cmd) -> dict[str,str|int|bytes|None]:
        if self._conn is None:
            raise Exception("SSH Connection not established")
        
        result = await self._conn.run(cmd, timeout=self.timeout, stderr=asyncssh.STDOUT)
        return {
            'output': result.stdout,
            'stdout': result.stdout,
            'stderr': result.stderr,
            'exit_status': result.returncode
        }
    
    async def execute_command(self, command: str, mitre_attack_technique: str, mitre_attack_procedure: str) -> str:
        """Execute a command over SSH and return the output.

        Parameters
        ----------
        command : str
            The command to execute.
        
        mitre_attack_technique : str
            The MITRE ATT&CK technique associated with the command.

        mitre_attack_procedure : str
            The MITRE ATT&CK procedure associated with the command.

        Returns
        -------
        str
            The output of the executed command.
        """
        try:
            return str((await self.run(command))['stdout'])
        except asyncssh.misc.ChannelOpenError:
            print("channel wasn't able to be opened, retrying...")
            await self.connect()
            return str((await self.run(command))['stdout'])
        except asyncssh.process.TimeoutError as e:
            return f"""Timeout during command execution over SSH command execution.
The command will be stopped, if files have been generated by the command they will be left on the system.

The output so far was:

```bash
{e.stdout}
```"""
    
def get_ssh_connection_from_env() -> SSHConnection:
    host = get_or_fail("TARGET_HOST")
    username = get_or_fail("TARGET_USERNAME")
    password = get_or_fail("TARGET_PASSWORD")

    return SSHConnection(host=host, username=username, password=password)
